
services:
  flappy-bird:
    build: .
    container_name: flappy-bird-game
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    restart: unless-stopped 